<?php

declare(strict_types=1);

use Symfony\Component\Config\Definition\Configurator\DefinitionConfigurator;

return static function (DefinitionConfigurator $definition): void {
    $definition->rootNode()
        ->children()
            ->scalarNode('url')
                ->info('Public absolute or relative URL of your OpenAPI document.')
                ->isRequired()
                ->cannotBeEmpty()
            ->end()
            ->scalarNode('cdn')
                ->info('URL of the Scalar API Reference standalone bundle.')
                ->defaultValue('https://cdn.jsdelivr.net/npm/@scalar/api-reference@1.65.1')
                ->cannotBeEmpty()
            ->end()
            ->scalarNode('path')
                ->info('Path of the API reference route.')
                ->defaultValue('/scalar')
                ->cannotBeEmpty()
                ->validate()
                    ->ifTrue(static fn (string $v): bool => !str_starts_with($v, '/'))
                    ->thenInvalid('The path must start with a slash ("/"), got "%s".')
                ->end()
            ->end()
            ->arrayNode('configuration')
                ->info('Well-known options merged into the Scalar.createApiReference() configuration.')
                ->normalizeKeys(false)
                ->addDefaultsIfNotSet()
                ->children()
                    ->scalarNode('theme')
                        ->info('Scalar theme: default, alternate, none, or any theme shipped with Scalar.')
                        ->defaultValue('default')
                    ->end()
                    ->scalarNode('_integration')
                        ->info('Integration identifier sent to Scalar (used for their usage stats).')
                        ->defaultValue('symfony')
                    ->end()
                    ->arrayNode('metaData')
                        ->info('Metadata passed to Scalar (title, description, ...).')
                        ->normalizeKeys(false)
                        ->defaultValue(['title' => 'API Reference'])
                        ->variablePrototype()
                    ->end()
                ->end()
            ->end()
            ->end()
            ->arrayNode('scalar_options')
                ->info('Any additional Scalar option, passed through verbatim (e.g. darkMode, layout, withSearch, hideClientButton).')
                ->normalizeKeys(false)
                ->defaultValue([])
                ->variablePrototype()
            ->end()
            ->end()
            ->arrayNode('access_control')
                ->info('Access control for the API reference route.')
                ->addDefaultsIfNotSet()
                ->children()
                    ->enumNode('mode')
                        ->info('"public" — everyone may view the docs; "attribute" — require a security attribute.')
                        ->values(['public', 'attribute'])
                        ->defaultValue('public')
                    ->end()
                    ->scalarNode('attribute')
                        ->info('Security attribute to check when mode is "attribute" (e.g. ROLE_ADMIN).')
                        ->defaultNull()
                        ->cannotBeEmpty()
                    ->end()
                ->end()
                ->validate()
                    ->ifTrue(static fn (array $v): bool => 'attribute' === $v['mode'] && null === $v['attribute'])
                    ->thenInvalid('An attribute is required when access_control.mode is "attribute".')
                ->end()
            ->end()
        ->end();
};
